### ISSUE TITLE
Some issues with the module

### ISSUE THREAD

**Issue by nmamn** [lvicainne/puppet-opendkim#1]
Hi,

I have ran accross several issues here.

1) https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=792458
I had to remove the end-of-line comments in opendkim.erb in order to get it to work (ubuntu 16.04) and uncomment the desired socket as well.

2) In Keytable.erb you're naming the key "<%= mykey['domain'] %>/<%= mykey['selector'] %>"
Whereas in config.pp you're naming it : "file { "${opendkim::configdir}/keys/${key['domain']}/default""

So opendkim is pointing at a file which does not exist (all privates keys are named "default")

I would probably replace it by "$key['selector'].private" in config.pp and <%= mykey['selector'] %>.private in Keytable.erb

3) same issue for the public key, they're all in files called "default.txt". I would use "$key['selector'].txt"

Thanks a lot

Nicolas

**Comment by HielkeJ** [comment]
Problems 2 and 3 are already fixed in the Github Master version. Can you release the new version to the Forge?

**Comment by lvicainne** [comment]
Hello !
First of all, thanks for your questions : I will be pleased to use your comments to imprive this module.

As @HielkeJ said, for problems 2 and 3, I corrected it some time ago, without publishing a new version of the module on the Puppet Forge.

For the 1st problem, I am quite interested. Because there are several files with the same name, could you just give the full pathname of the files which causes the error ?

Thanks 

Louis

**Comment by nmamn** [comment]
Hi,

I'm deeply sorry not to have answered before ...

I can see 1st problem was partially solved by the merge you made 11 days ago (for the missing socket part).

The other part of the problem was happening when uncommenting the following line for instance #SOCKET="inet:12345@192.0.2.1" # listen on 192.0.2.1 on port 12345
(from https://github.com/lvicainne/puppet-opendkim/blob/master/templates/sysconfig/opendkim.erb)

As stated in the debian bug report : "systemd environment files do *not* support in-line 
comments"

Thanks,

Nicolas

**Comment by lvicainne** [comment]
Hello,
No problem at all.
Thanks for this explanation. I've just corrected the template, according to your comment.
Do you agree ? In this case, I will update the Puppet Forge
Regards

**Comment by nmamn** [comment]
yes, seems perfect to me now :-)
